apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ivovle
  namespace: default
roleRef:
  kind: Role
  name: ivolve
  apiGroup: rbac.authorization.k8s.io

