# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ivolve
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlpdm9sdmU=  # Base64-encoded root password (example: user_root_password)
  MYSQL_PASSWORD: bXlpdm9sdmU=           # Base64-encoded user password (example: user_password)

