# namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ivolve
---
# resource-quota.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ivolve-quota
  namespace: ivolve
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"

