---
# roles/oc/tasks/main.yml

- name: Download oc binary
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
    dest: /tmp/openshift-client-linux.tar.gz

- name: Extract oc binary
  unarchive:
    src: /tmp/openshift-client-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Set executable permissions for oc
  file:
    path: /usr/local/bin/oc
    mode: '0755'
